#define SECRET_MQTT_USERNAME "LhsJACUpOSouBzgPKw0SCyU"
#define SECRET_MQTT_CLIENT_ID "LhsJACUpOSouBzgPKw0SCyU"
#define SECRET_MQTT_PASSWORD "Zrz4NdmikN+993mbydIqHxWD"

#define SECRET_WIFI_NAME "nnminh_asus_laptop"
#define SECRET_WIFI_PASSWORD "12345678"
#define CHANNEL_ID "2711831"
#define CHANNEL_WRITE_API_KEY "UULXX7OEH50YBQ1Y"
